### ISSUE TITLE
about the generate text, How to distinguish that which X is which slot

### ISSUE THREAD

**Issue by WoWuQ** [UFAL-DSG/tgen#31]
example:
generate text is:
     Take X line X from X to X at X .
da is:
 inform(line=X-line)&inform(direction=X-direction)&inform(from_stop=X-from_stop)&inform(departu    re_time=X-departure_time)&inform(vehicle=X-vehicle)

how can i distinguish that which x is which slot?

**Comment by tuetschek** [comment]
You need to preprocess the data using the `-n` parameter for `convert.py`, then retrain the system. I'm sorry about this – I used [Treex](http://ufal.cz/treex) and the `*-abst.txt` files to add the slot name information during preprocessing, and that's why the makefile didn't include it. I've fixed the problem in c3d7e4587249bfd59ab7c2d3a1044e16c39aad5f. Now running `make` in the `tgen/alex-context/input` directory should produce the files in the correct format (and does not require Treex). Hope this helps, please reopen the issue if not.
