### ISSUE TITLE
In seq2seq_train mode, what is rerank_classifier function?

### ISSUE THREAD

**Issue by WoWuQ** [UFAL-DSG/tgen#33]
when I run this command:
./run_tgen.py seq2seq_train config-file.py train-das.txt train-text.txt model.pickle.gz
and then run this command to generate text:
./run_tgen.py seq2seq_gen [-w out-text.txt] model.pickle.gz test-das.txt

I only watch the reranker's training, but i don't see seq2seq model use it  in both training and generating. 
Is it?  if not, could you tell me about rerank's function?
thanks.

**Comment by tuetschek** [comment]
Yes, it is working even if there is no trace of that on the console. You may use the `-d <debug-logfile>` parameter to get a more detailed generation log (look for "Misfits for DA" prints), but note that this output is very verbose, so it's better to test it on just a small number of input dialogue acts.

Also note that you need to set `beam_size` in the configuration file to a value larger than 1, otherwise the reranker would not have any effect.

The reranker function is basically the following: The main seq2seq generator produces _k_ outputs using beam search (_k_-best list). The reranker first tries to classify the dialogue act for each of these outputs, then compares the classification results to the input dialogue act. The number of discrepancies is used as a penalty to move the output down the _k_-best list. 

You can find a more detailed explanation on page 85-86 [of my thesis](http://bit.ly/dusek-nlg-thesis). A bit more descriptive picture is also in the [accompanying slides](https://ufal.mff.cuni.cz/~odusek/2018/docs/thesis-slides.pdf) (slide 13).
