### ISSUE TITLE
checkpoint at every epoch

### ISSUE THREAD

**Issue by giobin** [UFAL-DSG/tgen#39]
Hello,
I'm working on the E2E Challenge dataset and I'm wondering if there is a way to create a checkpoint of the system at every epoch during training. This way it will be possible to calculate the metrics after every epoch.

Thanks

**Comment by tuetschek** [comment]
Hi @giobin , 

thanks for your interest in TGen and E2E data and sorry for the extremely late answer. 

The system will currently create a checkpoint after every epoch if you set `validation_freq` in the config file to `1`, but only if the performance on the validation data is improved.

To change this behavior, you may want to change the code [here](https://github.com/UFAL-DSG/tgen/blob/master/tgen/seq2seq.py#L905), removing the `if` condition should do :-). You also might want to adapt the [`_save_checkpoint`](https://github.com/UFAL-DSG/tgen/blob/master/tgen/seq2seq.py#L992) method so that it uses a different file name each time.

Hope this helps. Let me know if you need more information.
