### ISSUE TITLE
Will GPU speed up seq2seq in e2e-challenge?

### ISSUE THREAD

**Issue by rivamarco** [UFAL-DSG/tgen#42]
Hi, i'm trying to run (in order to understand how it works) the e2e-challenge as described here https://github.com/UFAL-DSG/tgen/tree/master/e2e-challenge

All works but of course it takes time.

I would know if a configuration with an Nvidia GPU will increase the performance (among a CPU-only configuration) and reduce the time or it will be useless. I'm a beginner, i was reading that maybe LSTM doesn't benefit of GPU, so that's why I'm asking.

Thank you!

**Comment by tuetschek** [comment]
Hi @rivamarco, thanks for your interest in TGen! I myself don't have much experience with running on GPUs since they're harder to get at our institution and there's always plenty of free CPUs, so I just run models in parallel and wait a few hours. I think that the problem is exactly LSTMs (and you can switch to GRUs very easily). I think it also depends on your data size and batch size. 

The following is just a wild guess: I believe that in general, using a GPU will speed up the computation for an "average" NLG dataset, but I'd expect 2x-5x speedup at most, most probably not 10x or more.
