### ISSUE TITLE
How to produce output on the test dataset while doing in e2e-challenge dataset

### ISSUE THREAD

**Issue by Shubham1999-tech** [UFAL-DSG/tgen#46]

**Comment by tuetschek** [comment]
I've added some instructions in a4f10d0fb31406bf49e082b26fc70a7b065e4241 into [E2E readme](https://github.com/UFAL-DSG/tgen/blob/master/e2e-challenge/README.md). It should be relatively straightforward, but if you're unsure, let me know.

**Comment by Shubham1999-tech** [comment]
The instructions u wrote is regarding the development and training data and the outputs that were shown on dev- data. I was asking how we gonna convert our TEST data and then produce utterance based on it

**Comment by tuetschek** [comment]
Oh, right. The conversion script unfortunately isn't designed to work without references. After the conversion, the generator doesn't actually need the references (you can use `test-conc_das.txt` instead of `test-abst.txt` for the `-a` parameter, the result should be the same and you're not touching the references anywhere in the process).

I'll have a look at the conversion script to make it work without references, but it won't be immediate.

**Comment by tuetschek** [comment]
I've fixed the conversion script and added instructions in c0e6cade19a0bc9ac46dc5421d44d2e0c5a3cc67
